### ISSUE TITLE
<doc> tag

### ISSUE THREAD

**Issue by RedHatter** [htmlx-org/HTMLx#13]
What would you think of a `<doc></doc>` tag? It would be useful for tying documentation in with the component without resorting to big long javascript comment.

**Comment by arxpoetica** [comment]
Oh. That's a very compelling idea. Could even go a long way towards apps implementing their own methodology of transpiling in-app documentation into—whatever format needed...

**Comment by MaxMilton** [comment]
How would this be more useful than just using comments? Comments come out-of-the-box with all code editors and don't require anything extra. For rich and/or very long documentation I find it better to add a comment with a link to markdown generated docs for example.

**Comment by arxpoetica** [comment]
Yeah, actually the downfall of `<doc>` is that then it would have to be officially reserved, so I think @MaxMilton is right. Just comments.
